from Legion import Legion
from Campamento import Campamento

print("Creando ejército...")
legion_romana = Legion()
print("Ejército creado")
print("Composición actual: ")
print("- 0 unidades de combate")
print("- 0 oficiales")
print("  (número total de componentes: 0)")
print("Poblando ejército...")
legion_romana.poblar()
print("Ejército poblado")
print("Composición actual: ")
print(f"- {legion_romana.obtener_numero_soldados()} unidades de combate")
print(f"- {legion_romana.obtener_numero_oficiales()} oficiales")
print(f"  (número total de componentes: "
      f"{legion_romana.obtener_numero_soldados() + legion_romana.obtener_numero_oficiales()})")
print("Creando campamento...")
campamento_fijo = Campamento()
print("Campamento creado")
print("Estableciendo legión en el campamento")
campamento_fijo.establecer_legion(legion_romana)
print("Los soldados ya tienen un lugar donde descansar!")
campamento_fijo.obtener_armeria().hacer_inventario()
campamento_fijo.obtener_hospital().hacer_inventario()
legion_romana.establecer_armamento()
campamento_fijo.obtener_armeria().hacer_inventario()